# Site settings
title: Machine Learning in Drug Discovery & Development at Connecticut
email: shangchaocs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: 
github_username: mlddd-ct

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman